global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-local'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

alerting:
  alertmanagers:
    - static_configs:
#        - targets: [ 'alertmanager:9093' ]
        - targets: ['host.docker.internal:9093']